version: "3.8"

services:
  jaeger-server:
    image: jaegertracing/all-in-one:1.25
    container_name: jaeger-server
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9412:9411
    networks:
      - jaeger-network
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9412
    
volumes:
  jaeger-server-data:
    name: jaeger-server-data

networks:
  jaeger-network:
    name: jaeger-network
    driver: bridge
