version: "3.8"

services:
  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    networks:
      - portainer-network
        
volumes:
  portainer-data:
    name: portainer-data

networks:
  portainer-network:
    name: portainer-network
    driver: bridge
