version: "3.8"

services:
  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    networks:
      - portainer-network
    depends_on:
      - portainer-server

  portainer-server:
    image: portainer/portainer-ce
    container_name: portainer-server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - portainer-network
    
volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer-network:
    name: portainer-network
    driver: bridge
